### ISSUE TITLE
Refactoring deliverables and milestones sections?

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-wg-rpp-charter#10]
The deliverables sections now list activities and process description and not an overview of specifications and/or documents that are to be delivered?

The milestones section should be used to connect a timeline to the different deliverables?

as for example done by the DELEG wg?

see: https://datatracker.ietf.org/wg/deleg/about/

**Comment by anewton1998** [comment]
Not all charters look like DELEG. Take for instance MIMI: https://datatracker.ietf.org/group/mimi/about/

Milestones are actually managed by the datatracker, so there is no real need to put that in the charter itself.

The deliverables section is merely to communicate to the IESG and the rest of the IETF that the working group isn't gonna just do stuff without a plan. It isn't totally necessary (see MIMI), and making it too specific constrains the working group.

**Comment by mwullink** [comment]
maybe drop the milestones section then? and merge the text of the 2 sections into a single deliverables section?

**Comment by anewton1998** [comment]
To be clear, merge the milestones and deliverables section into a single deliverables section? If so, sounds good to me.

**Comment by mwullink** [comment]
yes, i'll create a PR

**Comment by mwullink** [comment]
created pull request #12
