### ISSUE TITLE
Requirements for WG Adoption

### ISSUE THREAD

**Issue by OR13** [SIDN/ietf-wg-rpp-charter#11]
For some new charters, I have heard discussion of asking chairs to:

"Explain how this document fits within the WG charter"

You can consider making this a requirement for the charter if you feel it would help.

If you feel this is not necessary, you can close this issue.

**Comment by anewton1998** [comment]
Aren't all new I-Ds under consideration for wg adoption subject to the scope of a charter? I guess I don't understand the request. Is it that the wg chair MUST provide a written statement regarding how an I-D fits within the WG charter?

**Comment by OR13** [comment]
Sometimes documents are adopted, where there is later some debate about if the document is in scope... Having this text available can help resolve those issues in the future, but you are correct... It should not be possible to adopt a document, which is out of the charter for the group.

**Comment by anewton1998** [comment]
@mwullink when you update the deliverables section, can you include this type of text? I think we should essentially say that a written record of acceptance with an explanation of WG scope of I-Ds as wg work items is to be recorded with explicit acknowledgement of the chairs.

**Comment by mwullink** [comment]
created pull request #12 

but i'm not sure about the text Any proposed above,  i feel its redundant because the IETF document adoption process should prevent the problems mentioned by Orie, right? maybe just leave it out? it might confuse readers?
