### ISSUE TITLE
Link between RPP and RDAP

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-wg-rpp-charter#19]
Do weed not to make the relationship between RPP and RDAP more explicit in the text?

**Comment by mwullink** [comment]
Maybe change: "The recent deployment of RDAP in the domain name industry demonstrates adoption of this type of architecture."

to:

The  successful adoption of RDAP by domain name registries and regional Internet registries (RIR) demonstrates the usefulness of this type of architecture and technology tool stack.

**Comment by pawel-kow** [comment]
This is a good proposal.
