### ISSUE TITLE
RPP - EPP Sync

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-wg-rpp-charter#20]
Do we need to add text describing how to make sure RPP and EPP stay in sync?

I feel, the text in [Coordination of work with other working groups](https://github.com/SIDN/ietf-wg-rpp-charter/blob/main/rpp-charter.md#coordination-of-work-with-other-working-groups) is maybe already covering it

**Comment by EricIO** [comment]
I think this text in the charter points to something like it.

> The RPP working group may however consider possibilities of mapping of data objects, operations and extensions from EPP to RPP for both clients and servers.

But it might be in need of a slight rewording IMHO. Perhaps something like this?

> The RPP working group may consider adapting any EPP extensions, operations, and data mappings produced by the REGEXT working group to RPP.

**Comment by anewton1998** [comment]
Related to #17 and #27
