### ISSUE TITLE
Coordination with entities outside of IETF

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-wg-rpp-charter#21]
Should we included text in the [Coordination of work with other working groups](https://github.com/SIDN/ietf-wg-rpp-charter/blob/main/rpp-charter.md#coordination-of-work-with-other-working-groups) section (and change the section name) that includes a reference to ICANN with regards to concerns raised over the ICANN RA process?

**Comment by anewton1998** [comment]
I don't see any such coordination callout in the charter for [REGEXT](https://datatracker.ietf.org/wg/regext/about/) and they seem to do just fine collaborating with ICANN. So I don't think it is necessary here.

**Comment by mwullink** [comment]
agree, can close this issues if nobody objects.

**Comment by pawel-kow** [comment]
I would be even against adding such dependency, especially that RPP is not anyhow related to ICANN at the moment. So please close it.
