### ISSUE TITLE
Incorrect EPP Timeline

### ISSUE THREAD

**Issue by shollenbeck** [SIDN/ietf-wg-rpp-charter#23]
Minor nit: the proposed charter currently says that "The Extensible Provisioning Protocol (EPP) was standardized (STD69) over 20 years ago". This isn't exactly correct. Standard 69 was published in August 2009, or a bit more than 15 years ago. The first Proposed Standard RFCs (3730 etc.) were published in March 2004. The sentence could be rewritten as either "The Extensible Provisioning Protocol (EPP) was standardized (STD69) over 15 years ago" or "The Extensible Provisioning Protocol (EPP) was first published as a series of Proposed Standards over 20 years ago". Pick one.

**Comment by pawel-kow** [comment]
Actually stating just a year would be more future proof than relative time (even if the sentence itself would remain true).

**Comment by anewton1998** [comment]
Fixed in #24
