### ISSUE TITLE
More explicit text, less 'may' or 'could'.

### ISSUE THREAD

**Issue by mdavids** [SIDN/ietf-wg-rpp-charter#35]
The concept charter uses words such as 'may' and 'could', where I would prefer the language to be just a little bit stronger:

https://github.com/SIDN/ietf-wg-rpp-charter/blob/6580546e376b543bd29767de7e5976e1f292e3ae/rpp-charter.md?plain=1#L7

I would prefer slightly different language, such as:

`Such design **is expected to** take advantage of stateless architecture and widely deployed solutions such as... ` instead of 'could'.

And  (for example):

`A REST architecture is chosen because it is expected to allow for easier integration between registries and registrars, thus lowering the costs for domain registration and new market entrants.` instead of 'may'.

**Comment by pawel-kow** [comment]
+1

**Comment by pawel-kow** [comment]
This was addressed with #38
