### ISSUE TITLE
Clarify REGEXT out-of-scope

### ISSUE THREAD

**Issue by jasdips** [SIDN/ietf-wg-rpp-charter#36]
> The REGEXT working group is chartered to maintain and standardize extensions to EPP, therefore extensions or changes for EPP, including those added by RPP, are explicitly out of scope for the RPP working group.

Found "including those added by RPP" phrase confusing. What does that mean?

**Comment by pawel-kow** [comment]
Hi @jasdips,
the intention was to mention, that RPP group would not work on EPP extension for the counterparts of RPP functionality not existing in EPP.

Reading it again I also can share your confusion. Would this text work better for you:
The REGEXT working group is chartered to maintain and standardize extensions to EPP. Consequently, any extensions or changes to EPP, including those related to RPP functionality that do not exist in EPP, are explicitly out of scope for the RPP working group.

**Comment by jasdips** [comment]
Perfect.

**Comment by rpp-ietf** [comment]
Pawel,

I don’t get the goal here.  It still has not been determined what is included and not included in RPP based on what has been defined for EPP, including the EPP extensions.  The goal of “RPP Overlap with EPP” should not include explicit out of scope items for the RPP working group in the charter as it related to EPP interoperability.    Please remove this sentence from the charter.

--

JG

***@***.***

James Gould
Fellow Engineer
***@***.******@***.***>

703-948-3271
12061 Bluemont Way
Reston, VA 20190

Verisign.com<http://verisigninc.com/>

From: Pawel Kowalik ***@***.***>
Reply-To: SIDN/ietf-wg-rpp-charter ***@***.***>
Date: Friday, November 15, 2024 at 12:31 PM
To: SIDN/ietf-wg-rpp-charter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [rpp] Re: [SIDN/ietf-wg-rpp-charter] Clarify REGEXT out-of-scope (Issue #36)


Caution: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @jasdips<https://secure-web.cisco.com/1mXDjtHI4poiW9Ezwfw2j5yL-YNvz0qOm5lDDai-pzD0GvKNgX1-vghfyOcIGANDLLOe_0KRBn8-TaHG6VCY5auxaDmDEdsA7z9bNbxpyHHw6eAKbj8ZKBmIglxlx-Ws-f-eZN_gKRbibhkvjT8OCQaoKPTZXbezWMgYLARkR3k-Mc5zn3U3BkWO36H7TfLk9XBaNFGDYWxML9uqWK_ow4nQ9RbiA8m4VN1_DChWcF7BjzFubthLgo6kRl-oF53fR5pwbJ5ZM3TCYr5ianDuxk9Y5zQxRH55HddcJUMRaX5o/https%3A%2F%2Fgithub.com%2Fjasdips>,
the intention was to mention, that RPP group would not work on EPP extension for the counterparts of RPP functionality not existing in EPP.

Reading it again I also can share your confusion. Would this text work better for you:
The REGEXT working group is chartered to maintain and standardize extensions to EPP. Consequently, any extensions or changes to EPP, including those related to RPP functionality that do not exist in EPP, are explicitly out of scope for the RPP working group.

**Comment by anewton1998** [comment]
The wording means that work on EPP is out of scope for the RPP working group, including creation of EPP extensions that are functional equivalents of RPP.

**Comment by rpp-ietf** [comment]
How about simplifying this to read?

“Creation of EPP extensions is out of scope for the RRP working group.”

We don’t need to specify why the EPP extensions are being created, but that all EPP extension work is out-of-scope for the RRP working group.

--

JG

***@***.***

James Gould
Fellow Engineer
***@***.******@***.***>

703-948-3271
12061 Bluemont Way
Reston, VA 20190

Verisign.com<http://verisigninc.com/>

From: Andrew Newton ***@***.***>
Reply-To: SIDN/ietf-wg-rpp-charter ***@***.***>
Date: Friday, November 15, 2024 at 2:50 PM
To: SIDN/ietf-wg-rpp-charter ***@***.***>
Cc: rpp-ietf ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] [rpp] Re: [SIDN/ietf-wg-rpp-charter] Clarify REGEXT out-of-scope (Issue #36)


Caution: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


The wording means that work on EPP is out of scope for the RPP working group, including creation of EPP extensions that are functional equivalents of RPP.

**Comment by mwullink** [comment]
+1

-
Maarten




How about simplifying this to read?

“Creation of EPP extensions is out of scope for the RRP working group.”

We don’t need to specify why the EPP extensions are being created, but that all EPP extension work is out-of-scope for the RRP working group.

--

JG

***@***.***

James Gould
Fellow Engineer
***@***.******@***.***>

703-948-3271
12061 Bluemont Way
Reston, VA 20190

Verisign.com<http://verisigninc.com/>

From: Andrew Newton ***@***.***>
Reply-To: SIDN/ietf-wg-rpp-charter ***@***.***>
Date: Friday, November 15, 2024 at 2:50 PM
To: SIDN/ietf-wg-rpp-charter ***@***.***>
Cc: rpp-ietf ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] [rpp] Re: [SIDN/ietf-wg-rpp-charter] Clarify REGEXT out-of-scope (Issue #36)


Caution: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


The wording means that work on EPP is out of scope for the RPP working group, including creation of EPP extensions that are functional equivalents of RPP.

**Comment by pawel-kow** [comment]
Addition to the text was aimed to address #20. I'm ok to go with simple text as well.

**Comment by anewton1998** [comment]
The current text says:

> The REGEXT working group is chartered to maintain and standardize extensions to EPP. Consequently, any extensions or changes to EPP, including those related to RPP functionality that do not exist in EPP, are explicitly out of scope for the RPP working group.

"any extensions or changes to EPP" covers the creation of EPP extensions. It seems to me and additional sentence of "Creation of EPP extensions is out of scope..." is both unnecessary and more wordy. I am inclined to close this issue absent a compelling reason not do so.

**Comment by jasdips** [comment]
TBH, I find the current paragraph more contextual. But, no strong opinion here if we go with James' suggestion.

**Comment by anewton1998** [comment]
> We don’t need to repeat the purpose of REGEXT or project the reasons why EPP extension work is out-of-scope.

The concern regarding the interplay between EPP and RPP has been brought up multiple times, so I'd prefer to keep the context. I'll let the AD determine if context needs to be removed.
