### ISSUE TITLE
REST architectural style and the JSON data-interchange format

### ISSUE THREAD

**Issue by shollenbeck** [SIDN/ietf-wg-rpp-charter#41]
Please add references for both the "REST architectural style" (https://ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm ?) and the "JSON data-interchange format" (RFC 8259?). They're core parts of the scope of this work, so we should have agreement on what those terms mean.

**Comment by pawel-kow** [comment]
This was addressed with #42
