### ISSUE TITLE
Minor editorial suggestions

### ISSUE THREAD

**Issue by jasdips** [SIDN/ietf-wg-rpp-charter#44]
> "(RFC5730,5731,5732,5733)"

This verbiage is used twice in the charter. Should we change it to "(RFC 5730, RFC 5731, RFC 5732, RFC 5733)" with hyperlinks for each RFC? (As we did in "[RFC 6570](https://datatracker.ietf.org/doc/html/rfc6570), [RFC 8288](https://datatracker.ietf.org/doc/html/rfc8288), [RFC 9421](https://datatracker.ietf.org/doc/html/rfc9421), [RFC 9652](https://www.rfc-editor.org/rfc/rfc9652.html)".)

> "mappings between RPP and EPP."

Extraneous period in the end?

> "other types of Internet registries (e.g. IP addresses)"

How about changing it to "other types of Internet registries (e.g., for IP addresses and autonomous system numbers)"?

**Comment by anewton1998** [comment]
I will be creating an omnibus cleanup PR and include these edits.

**Comment by anewton1998** [comment]
Addressed in #45
