### ISSUE TITLE
Requirements change process when do we need AD consultation?

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-wg-rpp-charter#46]
Do we need to involve the AD for each (small) change of the requirements when there is wg consensus about the proposed change?

I'm concerned about having a too elaborate process for potential many small requirement changes that may come up during the design process.

Maybe change the charter text to say that involving the AD is optional for small changes and that it is up to the chairs to determine if a larger requires consultation with the AD?

proposed new txt:

"Once established, these requirements may be changed through explicit working group consensus and, when the chairs determine it to be a major change,  in consultation with the group’s responsible Area Director."

**Comment by anewton1998** [comment]
I agree. Grammar and spelling mistakes and things of that magnitude should not require the AD. I'll incorporate this into the current PR>
